version: '3.8'

services:
  ml-datasets:
    build: .
    container_name: aaa-ml-datasets
    volumes:
      - .:/app
      - ./data:/data
    ports:
      - "8888:8888"
      - "6006:6006"
    environment:
      - PYTHONPATH=/app
    command: >
      bash -c "jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token=''" 